### ISSUE TITLE
Version 0.9.0 Fails to Install in NPM

### ISSUE THREAD

**Issue by bdbvb** [dylanparry/ceylon#3]
It complains about package.json not being there.

Version 0.8.0 works OK.

**Comment by dylanparry** [comment]
Hi,

I've just pushed a new version, 0.9.1, which fixes the problem. It looks like when 0.9.0 was pushed to npm it got corrupted somehow and was missing the package.json. No idea why that might be.

Thanks,

**Comment by bdbvb** [comment]
Works. Thanks!!
